name: Build Windows

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      - run: flutter create --platforms=windows --project-name deep_focus .
      - run: flutter pub get
      - run: flutter build windows --release

      - name: Zip release
        run: |
          cd build/windows/x64/runner/Release
          7z a -tzip ${{ github.workspace }}/DeepFocus-Windows.zip *

      - uses: actions/upload-artifact@v4
        with:
          name: DeepFocus-Windows
          path: DeepFocus-Windows.zip
